services:
  db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db/init-insecure.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: php:8.2-apache
    container_name: db-access-web
    volumes:
      - ./web:/var/www/html/
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASS: app_user
      DB_NAME: bank
    ports:
      - 80:80
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground;"
    depends_on:
      - db
